# Generated by Django 4.0 on 2022-02-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
