# Generated by Django 4.0 on 2022-02-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_information_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='adhar',
        ),
        migrations.RemoveField(
            model_name='information',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='information',
            name='last_name',
        ),
        migrations.AddField(
            model_name='information',
            name='array',
            field=models.JSONField(default=list),
        ),
    ]
